# Generated by Django 2.0 on 2020-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=100, verbose_name='Car Name')),
                ('Model', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=100)),
                ('Fuel_Type', models.CharField(max_length=100)),
                ('VIN_Code', models.CharField(max_length=100)),
                ('Mileage', models.CharField(max_length=100)),
            ],
        ),
    ]
